services:
  backend:
    container_name: react-fastify-starter-backend-prod
    build:
      context: ..
      dockerfile: server/Dockerfile
    networks:
      - react-fastify-starter-net
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
    env_file:
      - .env

networks:
  react-fastify-starter-net:
    driver: bridge